package tournament.presentation;
import java.util.*; import tournament.application.*; import tournament.domain.*;
public class TournamentConsoleUI {
 private final TournamentService tournamentService; private final MatchService matchService; private final StandingsService standingsService; private final DisputeService disputeService; private final AuditService auditService;
 public TournamentConsoleUI(TournamentService tournamentService,MatchService matchService,StandingsService standingsService,DisputeService disputeService,AuditService auditService){this.tournamentService=tournamentService;this.matchService=matchService;this.standingsService=standingsService;this.disputeService=disputeService;this.auditService=auditService;}
 public void start(){ Scanner sc=new Scanner(System.in); while(true){ System.out.println("\n1.Create tournament 2.Open registration 3.Register team 4.Add player 5.Close+Seed 6.Generate schedule 7.Start 8.Submit result 9.View standings 10.Open dispute 11.View audit 12.View summary 0.Exit"); System.out.print("Choice: "); String c=sc.nextLine().trim(); try{ switch(c){ case "1" -> { System.out.print("Name: "); String name=sc.nextLine(); System.out.print("Type (1=RR,2=ELIM): "); String t=sc.nextLine(); tournamentService.createTournament("organizer1",name,"2".equals(t)?TournamentType.ELIMINATION:TournamentType.ROUND_ROBIN);} case "2" -> tournamentService.openRegistration("organizer1"); case "3" -> { System.out.print("Team name: "); String team=sc.nextLine(); System.out.print("Captain id (captain1..4): "); String cid=sc.nextLine(); System.out.print("Captain display name: "); String cap=sc.nextLine(); tournamentService.registerTeam(cid,team,cap);} case "4" -> { System.out.print("Captain id: "); String cid=sc.nextLine(); System.out.print("Team: "); String team=sc.nextLine(); System.out.print("Player: "); String p=sc.nextLine(); tournamentService.addPlayerToTeam(cid,team,p);} case "5" -> tournamentService.closeRegistrationAndSeed("organizer1"); case "6" -> tournamentService.generateSchedule("organizer1"); case "7" -> tournamentService.startTournament("organizer1"); case "8" -> { System.out.print("Match ID: "); int id=Integer.parseInt(sc.nextLine()); System.out.print("Score team1: "); int a=Integer.parseInt(sc.nextLine()); System.out.print("Score team2: "); int b=Integer.parseInt(sc.nextLine()); matchService.submitResult("ref1",id,a,b);} case "9" -> showStandings(standingsService.getStandings()); case "10" -> { System.out.print("Match ID: "); int id=Integer.parseInt(sc.nextLine()); System.out.print("Reason: "); String r=sc.nextLine(); disputeService.openDispute("captain1",id,r);} case "11" -> showAuditLog(); case "12" -> showTournamentSummary(tournamentService.getCurrentTournament()); case "0" -> { return; } default -> System.out.println("Invalid"); } System.out.println("OK"); } catch(Exception e){ System.out.println("Error: "+e.getMessage()); } }}
 public void showTournamentSummary(Tournament t){ if(t==null){System.out.println("No tournament."); return;} System.out.println("\nTournament: "+t.getName()+" ["+t.getType()+"] State="+t.getState().getName()); System.out.println("Teams: "+t.getTeams().size()+" | Scheduler: "+t.getSchedulerStrategy().getName()); for(Team team:t.getTeams()) System.out.println("- "+team.getName()+" roster="+team.getRoster().size()); System.out.println("Matches:"); for(Match m:t.getMatches()) System.out.println("  #"+m.getId()+" "+m.getTeamOne().getName()+" vs "+m.getTeamTwo().getName()+" ["+m.getStatus()+"]"); }
 public void showStandings(List<StandingsEntry> standings){ System.out.println("\nStandings"); int rank=1; for(StandingsEntry s:standings) System.out.println(rank+++". "+s.getTeamName()+" | W:"+s.getWins()+" D:"+s.getDraws()+" L:"+s.getLosses()+" Pts:"+s.getPoints()); }
 public void showDisputes(List<Dispute> disputes){ System.out.println("\nDisputes"); for(Dispute d:disputes) System.out.println("Match "+d.getMatchId()+" | "+d.getStatus()+" | "+d.getReason()); }
 public void showAuditLog(){ System.out.println("\nAudit Log"); for(AuditEvent e:auditService.getAuditLog()) System.out.println(e); }
}
