package tournament.presentation;
import java.util.*;
 import tournament.application.*;
 import tournament.domain.*;
public class TournamentConsoleUI {
 private final TournamentFacade facade;

 public TournamentConsoleUI(TournamentFacade facade){this.facade=facade;}

 public void start(){ Scanner sc=new Scanner(System.in); while(true){ System.out.println("\n1.Create tournament 2.Open registration 3.Register team 4.Add player 5.Close+Seed 6.Generate schedule 7.Start 8.Submit result 9.View standings 10.Open dispute 11.View audit 12.View summary 13.Resolve dispute 14.Finalize 15.Cancel 0.Exit"); System.out.print("Choice: "); String c=sc.nextLine().trim(); try{ switch(c){ case "1" -> { System.out.print("Name: "); String name=sc.nextLine(); System.out.print("Type (1=RR,2=ELIM): "); String t=sc.nextLine(); facade.createTournament("organizer1",name,"2".equals(t)?TournamentType.ELIMINATION:TournamentType.ROUND_ROBIN);} case "2" -> facade.openRegistration("organizer1"); case "3" -> { System.out.print("Team name: "); String team=sc.nextLine(); System.out.print("Captain id (captain1..4): "); String cid=sc.nextLine(); System.out.print("Captain display name: "); String cap=sc.nextLine(); facade.registerTeam(cid,team,cap);} case "4" -> { System.out.print("Captain id: "); String cid=sc.nextLine(); System.out.print("Team: "); String team=sc.nextLine(); System.out.print("Player: "); String p=sc.nextLine(); facade.addPlayerToTeam(cid,team,p);} case "5" -> facade.closeRegistrationAndSeed("organizer1"); case "6" -> facade.generateSchedule("organizer1"); case "7" -> facade.startTournament("organizer1"); case "8" -> { System.out.print("Match ID: "); int id=Integer.parseInt(sc.nextLine()); System.out.print("Score team1: "); int a=Integer.parseInt(sc.nextLine()); System.out.print("Score team2: "); int b=Integer.parseInt(sc.nextLine()); facade.submitResult("ref1",id,a,b);} case "9" -> showStandings(facade.getStandings()); case "10" -> { System.out.print("Match ID: "); int id=Integer.parseInt(sc.nextLine()); System.out.print("Reason: "); String r=sc.nextLine(); facade.openDispute("captain1",id,r);} case "11" -> showAuditLog(); case "12" -> showTournamentSummary(facade.getCurrentTournament()); case "13" -> { System.out.print("Match ID: "); int id=Integer.parseInt(sc.nextLine()); System.out.print("Accept? (y/n): "); boolean accepted="y".equalsIgnoreCase(sc.nextLine().trim()); int na=0,nb=0; if(accepted){ System.out.print("New score team1: "); na=Integer.parseInt(sc.nextLine()); System.out.print("New score team2: "); nb=Integer.parseInt(sc.nextLine()); } facade.resolveDispute("organizer1",id,accepted,na,nb);} case "14" -> facade.finalizeTournament("organizer1"); case "15" -> facade.cancelTournament("organizer1"); case "0" -> { return; } default -> System.out.println("Invalid"); } System.out.println("OK"); } catch(Exception e){ System.out.println("Error: "+e.getMessage()); } }}
 public void showTournamentSummary(Tournament t){ if(t==null){System.out.println("No tournament."); return;} System.out.println("\nTournament: "+t.getName()+" ["+t.getType()+"] State="+t.getState().getName()); System.out.println("Teams: "+t.getTeams().size()+" | Scheduler: "+t.getSchedulerStrategy().getName()); for(Team team:t.getTeams()) System.out.println("- "+team.getName()+" roster="+team.getRoster().size()); System.out.println("Matches:"); for(Match m:t.getMatches()) System.out.println("  #"+m.getId()+" "+m.getTeamOne().getName()+" vs "+m.getTeamTwo().getName()+" ["+m.getStatus()+"]"+(m.getResult()!=null?" "+m.getResult().getTeamOneScore()+":"+m.getResult().getTeamTwoScore():"")); }
 public void showStandings(List<StandingsEntry> standings){ System.out.println("\nStandings"); int rank=1; for(StandingsEntry s:standings) System.out.println(rank+++". "+s.getTeamName()+" | W:"+s.getWins()+" D:"+s.getDraws()+" L:"+s.getLosses()+" Pts:"+s.getPoints()); }
 public void showDisputes(List<Dispute> disputes){ System.out.println("\nDisputes"); for(Dispute d:disputes) System.out.println("Match "+d.getMatchId()+" | "+d.getStatus()+" | "+d.getReason()); }
 public void showAuditLog(){ System.out.println("\nAudit Log"); for(AuditEvent e:facade.getAuditLog()) System.out.println(e); }
}
