package tournament.domain;
import java.util.*;
import tournament.domain.policy.*;
 import tournament.domain.state.*;
 import tournament.domain.strategy.SchedulerStrategy;
public class Tournament {
 private final String name; private final TournamentType type; private final RuleSetPolicy ruleSetPolicy; private final RosterSizePolicy rosterSizePolicy; private final DisputeWindowPolicy disputeWindowPolicy; private final SchedulerStrategy schedulerStrategy;
 private TournamentState state=new DraftState();
 private final List<Team> teams=new ArrayList<>(); private final List<Match> matches=new ArrayList<>(); private final List<Dispute> disputes=new ArrayList<>();
 public Tournament(String name,TournamentType type,RuleSetPolicy ruleSetPolicy,RosterSizePolicy rosterSizePolicy,DisputeWindowPolicy disputeWindowPolicy,SchedulerStrategy schedulerStrategy){ this.name=name; this.type=type; this.ruleSetPolicy=ruleSetPolicy; this.rosterSizePolicy=rosterSizePolicy; this.disputeWindowPolicy=disputeWindowPolicy; this.schedulerStrategy=schedulerStrategy; }
 public void openRegistration(){ state.openRegistration(this);} public void closeRegistrationAndSeed(){ state.closeRegistrationAndSeed(this);} public void generateSchedule(){ if(teams.size()<2) throw new IllegalStateException("Minimum team count not met"); matches.clear(); matches.addAll(schedulerStrategy.generateSchedule(teams)); state.generateSchedule(this);} public void startTournament(){ state.startTournament(this); matches.forEach(Match::start);} public void finalizeTournament(){ for(Match m:matches) if(m.getStatus()!=MatchStatus.FINALIZED) throw new IllegalStateException("All matches must be finalized before completing tournament"); state.finalizeTournament(this);} public void cancel(){ state.cancel(this);}
 public void registerTeam(Team team){ if(!state.getName().equals("RegistrationOpen")) throw new IllegalStateException("InvalidTournamentState"); if(findTeamByName(team.getName())!=null) throw new IllegalStateException("DuplicateTeamName"); teams.add(team);}
 public Team findTeamByName(String teamName){ return teams.stream().filter(t->t.getName().equalsIgnoreCase(teamName)).findFirst().orElse(null); }
 public Match findMatchById(int matchId){ return matches.stream().filter(m->m.getId()==matchId).findFirst().orElse(null); }
 public void addPlayerToTeam(String teamName, Player player){ Team team=findTeamByName(teamName); if(team==null) throw new IllegalArgumentException("Team not found"); for(Team t:teams) if(!t.getName().equalsIgnoreCase(teamName) && t.hasPlayerNamed(player.getName())) throw new IllegalStateException("Player already on another team"); team.addPlayer(player, rosterSizePolicy.getMaxRosterSize()); }
 public void addDispute(Dispute dispute){ disputes.add(dispute);}
 public List<StandingsEntry> calculateStandings(){ Map<String,StandingsEntry> map=new HashMap<>(); for(Team team:teams) map.put(team.getName(), new StandingsEntry(team.getName())); for(Match match:matches){ if(match.getStatus()!=MatchStatus.FINALIZED || match.getResult()==null) continue; MatchResult r=match.getResult(); if(r.isDraw()){ map.get(match.getTeamOne().getName()).recordDraw(ruleSetPolicy.getPointsForDraw()); map.get(match.getTeamTwo().getName()).recordDraw(ruleSetPolicy.getPointsForDraw()); } else { String winner=r.getWinnerTeamName(match); String loser=winner.equals(match.getTeamOne().getName())?match.getTeamTwo().getName():match.getTeamOne().getName(); map.get(winner).recordWin(ruleSetPolicy.getPointsForWin()); map.get(loser).recordLoss(); }} List<StandingsEntry> standings=new ArrayList<>(map.values()); standings.sort(Comparator.comparingInt(StandingsEntry::getPoints).reversed().thenComparing(StandingsEntry::getTeamName)); return standings; }
 public String getName(){return name;} public TournamentType getType(){return type;} public List<Team> getTeams(){return Collections.unmodifiableList(teams);} public List<Match> getMatches(){return matches;} public List<Dispute> getDisputes(){return disputes;} public TournamentState getState(){return state;} public void setState(TournamentState state){this.state=state;} public SchedulerStrategy getSchedulerStrategy(){return schedulerStrategy;} public DisputeWindowPolicy getDisputeWindowPolicy(){return disputeWindowPolicy;}
}
